---
# tasks file for launch_instances
- name: "installing boto3"
  pip:
        name: "boto3"

- name: "launching ec2-instances for kubernetes ..."
  ec2_instance:
        region: "{{ reg }}"
        image_id: "{{ img_id }}"
        instance_type: "{{ i_type }}"
        vpc_subnet_id: "{{ vpcsi }}"
        key_name: "{{ key }}"
        security_group: "{{ sg_group }}"
        name: "{{ kube_worker_name2 }}"
        state: present
        aws_access_key: "{{ aws_ak }}"
        aws_secret_key: "{{ aws_sk }}"
        volumes:
        - device_name: "/dev/xvda"
          ebs:
             volume_size: "{{ vol_size }}"
             delete_on_termination: true
        instance_tags:
             name: "{{ item.os }}"
        register: details
  loop: 
        - { os:  "{{ os_Name }}" }

